### PR TITLE
Expand on tests: add spinner test; add pytest, pytest-qt as extra reqs

### PR DESCRIPTION
**Pull request by psobolewskiPhD**
This PR cleans up and expands on the existing test.
A new test is added to test setting spinner values vs. resultant contrast settings.
A new test is added to test adding a non-image layer (shapes).
Also, optional requirements are added to enable testing (pytest, pytest-qt).

Edit: note, the non-image layer test will currently fail!

### CODE REVIEW

**Review by haesleinhuepf — APPROVED** [review]
Awesome, thanks @psobolewskiPhD ! You just taught me how to define optinal requirements. Thanks!

**Comment by psobolewskiPhD** [comment]
I did this test stuff to try and force myself to learn a bit more about tests...
Win win! These will have a fail until the other PR is merged, then will pass—at least I hope so!

**Comment by haesleinhuepf** [comment]
The tests are failing though @psobolewskiPhD 
Would you mind taking another look?

https://github.com/haesleinhuepf/napari-brightness-contrast/runs/5517198464?check_suite_focus=true#step:7:28

**Comment by psobolewskiPhD** [comment]
> The tests are failing though @psobolewskiPhD Would you mind taking another look?
> 
> https://github.com/haesleinhuepf/napari-brightness-contrast/runs/5517198464?check_suite_focus=true#step:7:28

The other PR is merged right? so the fix is in for shapes, so the tests *should* pass, so I guess I messed something up—I was trying to write a test for the fix, but without having the fix in it was a bit of a guess. It's probably something stupid, I'm sorry. I'll take a look and fix ASAP.

**Comment by psobolewskiPhD** [comment]
I think I got it—went from using layer by index to layer by name, but didn't actually name the layer. Should be passing now—pass for me locally.

**Comment by haesleinhuepf** [comment]
Awesome, thanks again Peter @psobolewskiPhD !

**Pull request merged**
